// Wave entries: { at: frame, kind, count, formation }
var StageData = [
    {
        id: 1, name: 'SPACE FRONT', scene: 'space',
        waves: [
            { at: 60,   kind: 'scout',       count: 3,  formation: 'line' },
            { at: 200,  kind: 'drone',        count: 5,  formation: 'swarm' },
            { at: 380,  kind: 'scout',        count: 5,  formation: 'V' },
            { at: 560,  kind: 'interceptor',  count: 4,  formation: 'sweep' },
            { at: 760,  kind: 'fighter',      count: 2 },
            { at: 960,  kind: 'scout',        count: 6,  formation: 'pincer' },
            { at: 1160, kind: 'drone',        count: 6,  formation: 'swarm' },
            { at: 1360, kind: 'gunship',      count: 1 },
            { at: 1560, kind: 'fighter',      count: 3 },
            { at: 1760, kind: 'bomber',       count: 1 },
            { at: 1960, kind: 'interceptor',  count: 5,  formation: 'sweep' },
            { at: 2160, kind: 'midboss',      count: 1 },
            { at: 2700, kind: 'fighter',      count: 4 },
            { at: 2900, kind: 'gunship',      count: 2 },
            { at: 3100, kind: 'drone',        count: 8,  formation: 'swarm' },
            { at: 3300, kind: 'bomber',       count: 2 },
            { at: 3500, kind: 'elite',        count: 1 },
            { at: 3700, kind: 'scout',        count: 6,  formation: 'line' },
            { at: 4000, kind: 'boss1',        count: 1 }
        ]
    },
    {
        id: 2, name: 'ASTEROID BELT', scene: 'asteroid',
        waves: [
            { at: 60,   kind: 'interceptor',  count: 4,  formation: 'sweep' },
            { at: 260,  kind: 'fighter',      count: 3 },
            { at: 460,  kind: 'drone',        count: 6,  formation: 'swarm' },
            { at: 660,  kind: 'bomber',       count: 2 },
            { at: 860,  kind: 'gunship',      count: 2 },
            { at: 1060, kind: 'fighter',      count: 4 },
            { at: 1260, kind: 'scout',        count: 6,  formation: 'V' },
            { at: 1460, kind: 'predator',     count: 1 },
            { at: 1560, kind: 'marauder',     count: 2 },
            { at: 1660, kind: 'elite',        count: 2 },
            { at: 1860, kind: 'interceptor',  count: 6,  formation: 'sweep' },
            { at: 2060, kind: 'bomber',       count: 2 },
            { at: 2260, kind: 'midboss2',     count: 1 },
            { at: 2800, kind: 'drone',        count: 8,  formation: 'swarm' },
            { at: 3000, kind: 'gunship',      count: 2 },
            { at: 3200, kind: 'elite',        count: 3 },
            { at: 3400, kind: 'carrier',      count: 1 },
            { at: 3600, kind: 'bomber',       count: 3 },
            { at: 3800, kind: 'predator',     count: 2 },
            { at: 4000, kind: 'fighter',      count: 5 },
            { at: 4300, kind: 'boss2',        count: 1 }
        ]
    },
    {
        id: 3, name: 'SOLAR STORM', scene: 'solar',
        waves: [
            { at: 60,   kind: 'predator',     count: 2 },
            { at: 260,  kind: 'drone',        count: 8,  formation: 'swarm' },
            { at: 360,  kind: 'spinner',      count: 3 },
            { at: 460,  kind: 'elite',        count: 3 },
            { at: 560,  kind: 'weaver',       count: 3,  formation: 'arc' },
            { at: 660,  kind: 'gunship',      count: 2 },
            { at: 860,  kind: 'interceptor',  count: 6,  formation: 'sweep' },
            { at: 1060, kind: 'fighter',      count: 5 },
            { at: 1160, kind: 'siren',        count: 2,  formation: 'line' },
            { at: 1260, kind: 'carrier',      count: 1 },
            { at: 1360, kind: 'vanguard',     count: 2 },
            { at: 1460, kind: 'bomber',       count: 3 },
            { at: 1660, kind: 'predator',     count: 2 },
            { at: 1760, kind: 'splitter',     count: 2 },
            { at: 1860, kind: 'elite',        count: 3 },
            { at: 2060, kind: 'scout',        count: 10, formation: 'V' },
            { at: 2260, kind: 'midboss2',     count: 1 },
            { at: 2800, kind: 'gunship',      count: 3 },
            { at: 3000, kind: 'drone',        count: 10, formation: 'swarm' },
            { at: 3200, kind: 'elite',        count: 4 },
            { at: 3400, kind: 'carrier',      count: 2 },
            { at: 3600, kind: 'bomber',       count: 4 },
            { at: 3800, kind: 'predator',     count: 3 },
            { at: 4000, kind: 'fighter',      count: 6 },
            { at: 4200, kind: 'midboss',      count: 1 },
            { at: 4800, kind: 'boss3',        count: 1 }
        ]
    },
    {
        id: 4, name: 'VOID ABYSS', scene: 'blackhole',
        waves: [
            { at: 60,   kind: 'predator',     count: 3 },
            { at: 260,  kind: 'interceptor',  count: 8,  formation: 'sweep' },
            { at: 460,  kind: 'drone',        count: 10, formation: 'swarm' },
            { at: 660,  kind: 'carrier',      count: 1 },
            { at: 760,  kind: 'siren',        count: 3,  formation: 'line' },
            { at: 860,  kind: 'gunship',      count: 3 },
            { at: 1060, kind: 'elite',        count: 4 },
            { at: 1160, kind: 'spectre',      count: 2 },
            { at: 1260, kind: 'predator',     count: 3 },
            { at: 1360, kind: 'weaver',       count: 5,  formation: 'grid' },
            { at: 1460, kind: 'bomber',       count: 4 },
            { at: 1660, kind: 'interceptor',  count: 8,  formation: 'sweep' },
            { at: 1860, kind: 'drone',        count: 12, formation: 'swarm' },
            { at: 2060, kind: 'midboss2',     count: 1 },
            { at: 2200, kind: 'devastator',   count: 1 },
            { at: 2400, kind: 'splitter',     count: 3,  formation: 'diagonal' },
            { at: 2600, kind: 'carrier',      count: 2 },
            { at: 2800, kind: 'predator',     count: 4 },
            { at: 3000, kind: 'gunship',      count: 4 },
            { at: 3200, kind: 'elite',        count: 5 },
            { at: 3400, kind: 'drone',        count: 14, formation: 'swarm' },
            { at: 3600, kind: 'interceptor',  count: 10, formation: 'sweep' },
            { at: 3800, kind: 'bomber',       count: 5 },
            { at: 4000, kind: 'carrier',      count: 2 },
            { at: 4200, kind: 'predator',     count: 4 },
            { at: 4500, kind: 'midboss',      count: 1 },
            { at: 5100, kind: 'boss4',        count: 1 }
        ]
    },
    {
        id: 5, name: 'NEBULA DEPTHS', scene: 'nebula',
        waves: [
            { at: 60,   kind: 'weaver',       count: 4,  formation: 'arc' },
            { at: 260,  kind: 'siren',        count: 2,  formation: 'line' },
            { at: 460,  kind: 'drone',        count: 10, formation: 'swarm' },
            { at: 660,  kind: 'splitter',     count: 3,  formation: 'grid' },
            { at: 860,  kind: 'interceptor',  count: 8,  formation: 'sweep' },
            { at: 1060, kind: 'weaver',       count: 5,  formation: 'grid' },
            { at: 1260, kind: 'predator',     count: 3 },
            { at: 1460, kind: 'siren',        count: 3,  formation: 'line' },
            { at: 1660, kind: 'elite',        count: 4 },
            { at: 1860, kind: 'spectre',      count: 2 },
            { at: 2060, kind: 'midboss2',     count: 1 },
            { at: 2600, kind: 'splitter',     count: 4,  formation: 'diagonal' },
            { at: 2800, kind: 'carrier',      count: 2 },
            { at: 3000, kind: 'weaver',       count: 6,  formation: 'arc' },
            { at: 3200, kind: 'siren',        count: 3,  formation: 'line' },
            { at: 3400, kind: 'elite',        count: 5 },
            { at: 3600, kind: 'bomber',       count: 4 },
            { at: 3800, kind: 'devastator',   count: 1 },
            { at: 4000, kind: 'predator',     count: 4 },
            { at: 4400, kind: 'boss5',        count: 1 }
        ]
    },
    {
        id: 6, name: 'PLASMA FLUX', scene: 'solar',
        waves: [
            { at: 60,   kind: 'predator',     count: 3 },
            { at: 260,  kind: 'gunship',      count: 3 },
            { at: 460,  kind: 'interceptor',  count: 10, formation: 'sweep' },
            { at: 660,  kind: 'spinner',      count: 4 },
            { at: 860,  kind: 'splitter',     count: 4,  formation: 'grid' },
            { at: 1060, kind: 'elite',        count: 5 },
            { at: 1260, kind: 'vanguard',     count: 3 },
            { at: 1460, kind: 'siren',        count: 3,  formation: 'line' },
            { at: 1660, kind: 'carrier',      count: 2 },
            { at: 1860, kind: 'marauder',     count: 3 },
            { at: 2060, kind: 'midboss',      count: 1 },
            { at: 2600, kind: 'weaver',       count: 6,  formation: 'arc' },
            { at: 2800, kind: 'spectre',      count: 3 },
            { at: 3000, kind: 'bomber',       count: 5 },
            { at: 3200, kind: 'predator',     count: 5 },
            { at: 3400, kind: 'elite',        count: 6 },
            { at: 3600, kind: 'devastator',   count: 1 },
            { at: 3800, kind: 'carrier',      count: 2 },
            { at: 4000, kind: 'splitter',     count: 5,  formation: 'hourglass' },
            { at: 4300, kind: 'midboss2',     count: 1 },
            { at: 4900, kind: 'boss6',        count: 1 }
        ]
    },
    {
        id: 7, name: "SOVEREIGN'S GATE", scene: 'blackhole',
        waves: [
            { at: 60,   kind: 'spectre',      count: 2 },
            { at: 260,  kind: 'devastator',   count: 1 },
            { at: 460,  kind: 'interceptor',  count: 10, formation: 'sweep' },
            { at: 660,  kind: 'siren',        count: 4,  formation: 'line' },
            { at: 860,  kind: 'splitter',     count: 5,  formation: 'grid' },
            { at: 1060, kind: 'elite',        count: 6 },
            { at: 1260, kind: 'weaver',       count: 6,  formation: 'arc' },
            { at: 1460, kind: 'carrier',      count: 2 },
            { at: 1660, kind: 'predator',     count: 5 },
            { at: 1860, kind: 'spectre',      count: 3 },
            { at: 2060, kind: 'boss8',        count: 1 },
            { at: 2700, kind: 'devastator',   count: 2 },
            { at: 2900, kind: 'elite',        count: 6 },
            { at: 3100, kind: 'siren',        count: 4,  formation: 'line' },
            { at: 3300, kind: 'splitter',     count: 6,  formation: 'diagonal' },
            { at: 3500, kind: 'carrier',      count: 3 },
            { at: 3700, kind: 'spectre',      count: 4 },
            { at: 3900, kind: 'devastator',   count: 2 },
            { at: 4200, kind: 'midboss2',     count: 1 },
            { at: 5000, kind: 'boss7',        count: 1 }
        ]
    }
];
